filebeatConfig:
  filebeat.yml: |
    filebeat.inputs:
    - type: container
      paths:
        - /var/log/containers/*.log
      processors:
      - add_kubernetes_metadata:
          host: ${NODE_NAME}
          matchers:
          - logs_path:
              logs_path: "/var/log/containers/"

    output.logstash:
      hosts: ["logstash-logstash:5044"]
resources:
  requests:
    cpu: "100m"
    memory: "500Mi"
  limits:
    cpu: "500m"
    memory: "1000Mi"
